language: csharp
solution: Descriptor.sln
install:
  - nuget restore Descriptor.sln
  - nuget install xunit.runner.console -Pre -Version 2.0.0-rc4-build2924 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Descriptor.sln
  - mono ./testrunner/xunit.runner.console.2.0.0-rc4-build2924/tools/xunit.console.exe ./tests/Descriptor.Tests/bin/Release/RimDev.Descriptor.Tests.dll
